### ISSUE TITLE
Critical Flow Documentation - Ad-Refresh-Control

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/Ad-Refresh-Control#154]
### Objective: 

This GitHub issue will serve as a task to prepare Critical Flow (also known as Test Cases) for this repository/plugin.
- **[Guide for Creating Critical Flow of 10up OSS Projects](https://docs.google.com/document/d/1rNv_jHxsQT-AKSJ9QC2HGH-rRKAlTJOoGBtP10w_zV0/edit#heading=h.ucn4farfwxyf).**

**Please comment on this issue if you don't have:**

-  Access to edit Wiki Pages
-  The repository does not have a Wiki Page enabled

**Comment by sudip-md** [comment]
@ankitguptaindia I have completed Critical Flow Documentation of Ad-Refresh-Control plugin. you can founded [here](https://github.com/10up/Ad-Refresh-Control/wiki/Testing-instructions-for-critical-flows)
