### ISSUE TITLE
Test against WordPress 5.7

### ISSUE THREAD

**Issue by jeffpaul** [10up/Ad-Refresh-Control#32]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.7 is released, we'll want to test Ad Refresh Control to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Ad Refresh Control on WordPress 5.7
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by darylldoyle** [comment]
@jeffpaul @davidrgreen I've tested this with `5.7-RC3-20210309.100012` and all seems to be working as expected there. 

Let me know if there's anything else I can do to help test this!
