### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [10up/Ad-Refresh-Control#62]
### Is your enhancement related to a problem? Please describe.

Once WordPress 6.0 is released, we'll want to test Ad Refresh Control to see if any incompatibility issues arise.

- [x]  test Ad Refresh Control on WordPress 6.0
- [x]  open issues for any incompatibilities noted in testing
- [x]  resolve issues identified in testing
- [x]  bump "tested up to" version
- [ ]  if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

### Designs

n/a

### Describe alternatives you've considered

none

**Additional context**
Related: #52, #32 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
#65 discovered during tests. Looks like it is not related to WordPress 6.0 update, the same issue happens in 5.9
